services:
  runner:
    image: glatzel-github-runner-win:ltsc2022
    build:
      context: ..
      args:
        BASE_IMAGE: "mcr.microsoft.com/windows/servercore:ltsc2022"
        RUNNER_VERSION: "2.321.0"
    env_file:
      - ./example/.env